Repository simple-icons/svglint, pull requests merged in 2022-10, with the labels that each got.

#68 chore: update supported Node.js versions & testing
  .github/workflows/test.yml
  package.json
Labels: enhancement

#70 chore(deps): bump actions/checkout from v2 to v3
  .github/workflows/release.yml
  .github/workflows/test.yml
Labels: dependencies

#69 chore(deps): bump actions/setup-node from v2 to v3
  .github/workflows/release.yml
  .github/workflows/test.yml
Labels: dependencies

#64 feat: autodiscover ESM and CJS configuration files
  bin/cli.js
  src/cli/config.js
  test/cli.spec.js
  test/projects/cjs/bar/.svglintrc.js
  test/projects/cjs/bar/a/b/c/.keep
  test/projects/cjs/bar/package.json
  test/projects/cjs/foo/.svglintrc.mjs
  test/projects/cjs/foo/package.json
  test/projects/esm/bar/.svglintrc.cjs
  test/projects/esm/bar/package.json
  test/projects/esm/foo/.svglintrc.js
  test/projects/esm/foo/custom-svglint-config.js
  test/projects/esm/foo/package.json
Labels: enhancement

#73 chore(deps): bump minimatch from 3.0.4 to 3.1.2
  package-lock.json
Labels: dependencies

#66 feat: set exit code depending on what went wrong
  .eslintrc.yaml
  bin/cli.js
  test/cli.spec.js
  test/projects/broken/broken-svglint-config.js
Labels: enhancement, help wanted
